export type { INavbarLinks } from './navbar.interface'
export type { TAuthStatus } from './auth-status.interface'
export type { IAuthUser } from './user.interface'
export type * from './modules/modules.interface'
export type * from './services-errors.interface'
